import mongoose from "mongoose";
import Book from "./models/Book.js";
import Settings from "./models/Settings.js";

const MONGO_URI = "mongodb://localhost:27017/oldbooksstore";

const newBooks = [
  // J.K. Rowling (68315d111111111111111114, Category: Fiction: 68315d222222222222222224)
  {
    title: "Harry Potter and the Chamber of Secrets",
    slug: "harry-potter-and-the-chamber-of-secrets",
    author: "68315d111111111111111114",
    category: "68315d222222222222222224",
    description: "The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/81S0nNQVE5L.jpg"],
    originalPrice: 999,
    discountedPrice: 850,
    discountPercentage: 15,
    stock: 12,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 341,
    condition: "New",
    featured: true,
    bestseller: true,
    trending: true,
    recommended: true,
    averageRating: 4.8,
    totalReviews: 240,
    publisher: "Scholastic",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "1998",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    slug: "harry-potter-and-the-prisoner-of-azkaban",
    author: "68315d111111111111111114",
    category: "68315d222222222222222224",
    description: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/81lAPl9Fl0L.jpg"],
    originalPrice: 1100,
    discountedPrice: 950,
    discountPercentage: 14,
    stock: 8,
    bookType: "Old",
    conditionDetails: "Slight wear on spine, clean pages",
    bindingType: "Hard Binding",
    totalPages: 435,
    condition: "Used",
    featured: false,
    bestseller: true,
    trending: false,
    recommended: true,
    averageRating: 4.9,
    totalReviews: 310,
    publisher: "Scholastic",
    bookFormat: "Hardcover",
    language: "English",
    publicationYear: "1999",
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    slug: "harry-potter-and-the-goblet-of-fire",
    author: "68315d111111111111111114",
    category: "68315d222222222222222224",
    description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter—but that doesn't stop Harry dreaming that he will win the competition.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/81t2CV8vGyL.jpg"],
    originalPrice: 1250,
    discountedPrice: 1100,
    discountPercentage: 12,
    stock: 5,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 734,
    condition: "New",
    featured: true,
    bestseller: false,
    trending: true,
    recommended: false,
    averageRating: 4.7,
    totalReviews: 185,
    publisher: "Scholastic",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2000",
  },

  // Cal Newport (68315d111111111111111115, Category: Self-Help: 68315d222222222222222222)
  {
    title: "Digital Minimalism",
    slug: "digital-minimalism",
    author: "68315d111111111111111115",
    category: "68315d222222222222222222",
    description: "A practical guide to reclaiming our attention, focusing on what truly matters, and building a more meaningful life in a hyper-connected world.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/41-AQA4lH6L._SX329_BO1,204,203,200_.jpg"],
    originalPrice: 850,
    discountedPrice: 750,
    discountPercentage: 12,
    stock: 15,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 302,
    condition: "New",
    featured: true,
    bestseller: true,
    trending: true,
    recommended: true,
    averageRating: 4.5,
    totalReviews: 145,
    publisher: "Portfolio",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2019",
  },
  {
    title: "So Good They Can't Ignore You",
    slug: "so-good-they-cant-ignore-you",
    author: "68315d111111111111111115",
    category: "68315d222222222222222222",
    description: "Newport debunks the belief that 'following your passion' is good career advice, showing instead that skill and craftsmanship are what build deep satisfaction.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/51wXpQA9x3L._SX329_BO1,204,203,200_.jpg"],
    originalPrice: 800,
    discountedPrice: 680,
    discountPercentage: 15,
    stock: 6,
    bookType: "Old",
    conditionDetails: "Good condition, no highlights",
    bindingType: "Paperback",
    totalPages: 288,
    condition: "Used",
    featured: false,
    bestseller: true,
    trending: false,
    recommended: true,
    averageRating: 4.6,
    totalReviews: 98,
    publisher: "Grand Central Publishing",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2012",
  },
  {
    title: "A World Without Email",
    slug: "a-world-without-email",
    author: "68315d111111111111111115",
    category: "68315d222222222222222222",
    description: "Reimagining work in an age of communication overload, Newport shows how organizations can escape the hyperactive hive mind and increase both productivity and peace.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/41T-m4fpxkL._SX327_BO1,204,203,200_.jpg"],
    originalPrice: 950,
    discountedPrice: 890,
    discountPercentage: 6,
    stock: 4,
    bookType: "New",
    bindingType: "Hard Binding",
    totalPages: 320,
    condition: "New",
    featured: true,
    bestseller: false,
    trending: true,
    recommended: false,
    averageRating: 4.3,
    totalReviews: 42,
    publisher: "Portfolio",
    bookFormat: "Hardcover",
    language: "English",
    publicationYear: "2021",
  },

  // James Clear (68315d111111111111111111, Category: Self-Help: 68315d222222222222222222)
  {
    title: "Atomic Habits Journal",
    slug: "atomic-habits-journal",
    author: "68315d111111111111111111",
    category: "68315d222222222222222222",
    description: "The ultimate companion to James Clear's groundbreaking book, designed to help you track habits, reflect on progress, and design your daily routines.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/81iWvF9N4BL.jpg"],
    originalPrice: 650,
    discountedPrice: 550,
    discountPercentage: 15,
    stock: 20,
    bookType: "New",
    bindingType: "Spiral Binding",
    totalPages: 224,
    condition: "New",
    featured: true,
    bestseller: true,
    trending: true,
    recommended: true,
    averageRating: 4.7,
    totalReviews: 89,
    publisher: "Avery",
    bookFormat: "Spiral Bound",
    language: "English",
    publicationYear: "2018",
  },
  {
    title: "3-2-1 Wisdom Anthology",
    slug: "3-2-1-wisdom-anthology",
    author: "68315d111111111111111111",
    category: "68315d222222222222222222",
    description: "A compiled anthology of thoughts, ideas, and quotes from James Clear's famous weekly newsletters focusing on self-mastery, focus, and decision making.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/41gPqOaQ6DL.jpg"],
    originalPrice: 450,
    discountedPrice: 400,
    discountPercentage: 11,
    stock: 10,
    bookType: "Old",
    conditionDetails: "Cover slightly bent, clean pages",
    bindingType: "Paperback",
    totalPages: 150,
    condition: "Used",
    featured: false,
    bestseller: false,
    trending: false,
    recommended: true,
    averageRating: 4.4,
    totalReviews: 32,
    publisher: "Self-Published",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2020",
  },
  {
    title: "Mastery of Tiny Behaviors",
    slug: "mastery-of-tiny-behaviors",
    author: "68315d111111111111111111",
    category: "68315d222222222222222222",
    description: "An advanced guide digging deeper into behavioural psychological research to sustain massive lifestyle modifications over decades.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/51wU0eA9xKL.jpg"],
    originalPrice: 899,
    discountedPrice: 799,
    discountPercentage: 11,
    stock: 5,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 312,
    condition: "New",
    featured: true,
    bestseller: true,
    trending: false,
    recommended: false,
    averageRating: 4.6,
    totalReviews: 28,
    publisher: "Avery",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2022",
  },

  // Robert Kiyosaki (68315d111111111111111112, Category: Business & Finance: 68315d222222222222222223)
  {
    title: "Rich Dad's Cashflow Quadrant",
    slug: "rich-dads-cashflow-quadrant",
    author: "68315d111111111111111112",
    category: "68315d222222222222222223",
    description: "Guide to Financial Freedom. It reveals how some people work less, earn more, pay less in taxes, and learn to become financially free.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/51f8vK9B3xL._SX331_BO1,204,203,200_.jpg"],
    originalPrice: 900,
    discountedPrice: 799,
    discountPercentage: 11,
    stock: 14,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 376,
    condition: "New",
    featured: true,
    bestseller: true,
    trending: true,
    recommended: true,
    averageRating: 4.6,
    totalReviews: 198,
    publisher: "Plata Publishing",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "1998",
  },
  {
    title: "Rich Dad's Guide to Investing",
    slug: "rich-dads-guide-to-investing",
    author: "68315d111111111111111112",
    category: "68315d222222222222222223",
    description: "What the rich invest in that the poor and middle class do not! Learn the rules of investing, reduce investment risk, and convert earned income into passive income.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/51F0D4w3hKL.jpg"],
    originalPrice: 999,
    discountedPrice: 850,
    discountPercentage: 15,
    stock: 9,
    bookType: "Old",
    conditionDetails: "Good overall condition, slight pencil marks on 3 pages",
    bindingType: "Paperback",
    totalPages: 400,
    condition: "Used",
    featured: false,
    bestseller: true,
    trending: false,
    recommended: true,
    averageRating: 4.5,
    totalReviews: 120,
    publisher: "Plata Publishing",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2012",
  },
  {
    title: "Retire Young Retire Rich",
    slug: "retire-young-retire-rich",
    author: "68315d111111111111111112",
    category: "68315d222222222222222223",
    description: "How to get rich quickly and stay rich forever. This book covers how Kiyosaki started from nothing and retired in less than 10 years by using financial leverage.",
    images: ["https://images-na.ssl-images-amazon.com/images/I/51A31B8wS4L.jpg"],
    originalPrice: 850,
    discountedPrice: 799,
    discountPercentage: 6,
    stock: 7,
    bookType: "New",
    bindingType: "Paperback",
    totalPages: 395,
    condition: "New",
    featured: true,
    bestseller: false,
    trending: true,
    recommended: false,
    averageRating: 4.4,
    totalReviews: 87,
    publisher: "Plata Publishing",
    bookFormat: "Paperback",
    language: "English",
    publicationYear: "2002",
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to MongoDB for seeding...");

    // Delete existing books with matching slugs to re-seed clean details
    const slugs = newBooks.map((b) => b.slug);
    const deleteRes = await Book.deleteMany({ slug: { $in: slugs } });
    console.log(`Cleaned up ${deleteRes.deletedCount} existing seeded books.`);

    // Insert new books
    const insertRes = await Book.insertMany(newBooks);
    console.log(`Successfully seeded ${insertRes.length} books with complete specifications!`);

    // Clean and seed settings
    await Settings.deleteMany({});
    const bookIds = insertRes.slice(0, 5).map((b) => b._id);
    
    await Settings.create({
      supportEmail: "support@bookworld.site",
      supportPhone: "+92 300 1234567",
      socialLinks: {
        facebook: "https://facebook.com/bookworld",
        instagram: "https://instagram.com/bookworld",
        whatsapp: "https://wa.me/923001234567",
        youtube: "https://youtube.com/bookworld",
      },
      paymentMethods: {
        jazzcash: {
          number: "03001234567",
          accountTitle: "Book World Store",
        },
        easypaisa: {
          number: "03121234567",
          accountTitle: "Book World Store",
        },
        bankTransfer: {
          bankName: "Meezan Bank Limited",
          accountNumber: "02340102030405",
          accountTitle: "Book World",
        },
      },
      useFlatDeliveryRate: true,
      flatDeliveryRate: 150,
      homepageSections: {
        hero: true,
        highDiscount: true,
        bestSeller: true,
        featuredBooks: true,
        trendingAuthors: true,
        trendingCategories: true,
        newReleases: true,
        trendingThisWeek: true,
        offersThisWeek: true,
      },
      heroSection: {
        category: "68315d222222222222222224", // Default to Fiction
        books: bookIds,
        button1Text: "SELL YOUR BOOK",
        button1Link: "/sell-book",
        button2Text: "CHOOSE FROM US",
        button2Link: "/books",
        primaryLine: "Where Every Page\u00A0Whispers History.",
        secondaryLine: "Rare Volumes. Timeless\u00A0Souls."
      },
      promoSection: {
        tagline: "✦ LIMITED TIME OFFER ✦",
        headline: "Enjoy an Exclusive",
        discountValue: 40,
        subCopy: "On all rare & collectible editions — this weekend only",
        buttonText: "SHOP NOW",
        buttonLink: "/books?promo=true",
        promoCode: "RARE40",
        isActive: true,
        endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        discountBooks: bookIds.slice(0, 2),
      },
      discountStrip: {
        text: "✦ Eid Special Offer ✦",
        offerContent: "Flat 40% Off on Premium Rare Collections",
        backgroundColor: "#c8860a",
        textColor: "#ffffff",
        promotionalLabel: "Limited Time Only",
        announcement: "Free Shipping on Orders above Rs. 2000!",
        isActive: true,
      },
      seo: {
        title: "BookWorld | Online Rare & Used Books Store",
        description: "Explore a premium collection of rare, vintage, and second-hand books at Book World.",
        keywords: "old books, used books, bookstore, novels",
      },
      loginContent: {
        eyebrow: "Bookstore Account",
        title: "Welcome Back",
        subtitle: "Login to continue your reading journey",
      },
      emailTemplates: {
        orderConfirmationSubject: "Order Confirmed - {orderNumber}",
        orderConfirmationBody: "Thank you for shopping with us! Your order has been received and is being processed.",
        orderUpdateSubject: "Order Update - {orderNumber} is now {orderStatus}",
        orderUpdateBody: "We wanted to let you know that the status of your order {orderNumber} has been updated to {orderStatus}.",
        paymentFailureSubject: "Payment Failed - Order {orderNumber}",
        paymentFailureBody: "We were unable to verify your payment for order {orderNumber}. Please check details, try again, or contact support.",
        feedbackSubject: "We'd love your feedback! - Order {orderNumber}",
        feedbackBody: "How did you like your books and our service? Please share a review on the store!",
        newsletterWelcomeSubject: "Welcome to Our Newsletter!",
        newsletterWelcomeBody: "Thank you for subscribing! You are on our list, we will inform you about our rare books and updates.",
        connectWelcomeSubject: "Thank you for connecting with us!",
        connectWelcomeBody: "You are on our list, we will inform you. We'll be in touch shortly!",
      }
    });
    console.log("Successfully seeded Settings collection!");

    console.log("Seeding completed successfully!");
  } catch (error) {
    console.error("Seeding error:", error);
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
  }
}

seed();
